INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (1, 'Really Awesome Song', 'A Great Band', 'R&B', '2007-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (2, 'Another Hit', 'Another Band', 'Pop', '2010-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (3, 'Smooth Jazz', 'Jazz Masters', 'Jazz', '2015-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (4, 'Rock Anthem', 'Rock Legends', 'Rock', '2000-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (5, 'Country Roads', 'Country Stars', 'Country', '1995-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (6, 'Hip Hop Beat', 'Hip Hop Heroes', 'Hip Hop', '2012-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (7, 'Classical Symphony', 'Orchestra', 'Classical', '1800-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (8, 'Reggae Vibes', 'Reggae Icons', 'Reggae', '1980-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (9, 'Electronic Dance', 'EDM Artists', 'Electronic', '2020-01-01');
INSERT INTO songs (song_id, title, artist, genre, release_date) VALUES (10, 'Blues Melody', 'Blues Band', 'Blues', '1975-01-01');
